---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "**/__tests__/*.test.js"
postMerge:
  pattern: 
    - "**/__tests__/*.test.js"
postRun:
     command:
        - yarn --version
version: 1.0.0
