name: 'Tests'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: 'lint (node: ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - uses: ./.github/actions/install-modules
      - name: Run lint
        run: yarn run -s lint
      - name: Run tests
        run: yarn run test:unit
  
